import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Iphone16Pro1(),
        ]),
      ),
    );
  }
}

class Iphone16Pro1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 402,
          height: 874,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(
            color: const Color(0xFFFCFCFC) /* white */,
            boxShadow: [
              BoxShadow(
                color: Color(0x3F000000),
                blurRadius: 4,
                offset: Offset(0, 4),
                spreadRadius: 0,
              )
            ],
          ),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 402,
                  height: 105,
                  decoration: BoxDecoration(
                    color: const Color(0xFF4E95CB) /* bruin-blue */,
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 41,
                child: Container(
                  width: 402,
                  height: 804,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 19,
                        top: 725.27,
                        child: Container(
                          width: 364,
                          height: 78.73,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 10,
                                top: 6,
                                child: Container(
                                  width: 102,
                                  height: 67,
                                  decoration: BoxDecoration(color: const Color(0x00D9D9D9)),
                                ),
                              ),
                              Positioned(
                                left: 256,
                                top: 9,
                                child: Container(
                                  width: 94,
                                  height: 62,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFFFCFCFC),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(100),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 10,
                                top: 6,
                                child: Container(
                                  width: 102,
                                  height: 67,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 102,
                                          height: 67,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                        ),
                                      ),
                                      Positioned(
                                        left: 26,
                                        top: 8,
                                        child: Container(width: 50, height: 51, child: Stack()),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 131,
                                top: 6,
                                child: Container(
                                  width: 102,
                                  height: 67,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 102,
                                          height: 67,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 252,
                                top: 6,
                                child: Container(
                                  width: 102,
                                  height: 67,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 102,
                                          height: 67,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 402,
                          height: 719.37,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 35,
                                top: 7,
                                child: SizedBox(
                                  width: 299,
                                  height: 59.05,
                                  child: Text(
                                    'Profile',
                                    style: TextStyle(
                                      color: const Color(0xFFFCFCFC) /* white */,
                                      fontSize: 40,
                                      fontFamily: 'Roboto',
                                      fontWeight: FontWeight.w600,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 65,
                                child: Container(
                                  width: 402,
                                  height: 660,
                                  padding: const EdgeInsets.all(10),
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(color: Colors.white),
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    spacing: 10,
                                    children: [
                                      Text(
                                        'PROFILE',
                                        style: TextStyle(
                                          color: Colors.black,
                                          fontSize: 24,
                                          fontFamily: 'Roboto',
                                          fontWeight: FontWeight.w500,
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}