// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHIw9tWqNp7E_bMsFO5ng2N4v7CCMC-Ik',
    appId: '1:524201570404:web:35fb8c857fd432e48caf71',
    messagingSenderId: '524201570404',
    projectId: 'need1more-1ebd9',
    authDomain: 'need1more-1ebd9.firebaseapp.com',
    databaseURL: 'https://need1more-1ebd9-default-rtdb.firebaseio.com',
    storageBucket: 'need1more-1ebd9.firebasestorage.app',
    measurementId: 'G-R59Q5JDKEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeTghrudaSaMCA3vrUpyrw0cCr8zzTgd0',
    appId: '1:524201570404:android:26e84c54fb8eb7358caf71',
    messagingSenderId: '524201570404',
    projectId: 'need1more-1ebd9',
    databaseURL: 'https://need1more-1ebd9-default-rtdb.firebaseio.com',
    storageBucket: 'need1more-1ebd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcvcEWXuod_qAP5u70uZa5ITRfEDr7Ng8',
    appId: '1:524201570404:ios:bbe60147174ff9698caf71',
    messagingSenderId: '524201570404',
    projectId: 'need1more-1ebd9',
    databaseURL: 'https://need1more-1ebd9-default-rtdb.firebaseio.com',
    storageBucket: 'need1more-1ebd9.firebasestorage.app',
    iosClientId: '524201570404-8go24ti4cop77sch9r05o2d0ghu5cv07.apps.googleusercontent.com',
    iosBundleId: 'com.example.plus1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcvcEWXuod_qAP5u70uZa5ITRfEDr7Ng8',
    appId: '1:524201570404:ios:bbe60147174ff9698caf71',
    messagingSenderId: '524201570404',
    projectId: 'need1more-1ebd9',
    databaseURL: 'https://need1more-1ebd9-default-rtdb.firebaseio.com',
    storageBucket: 'need1more-1ebd9.firebasestorage.app',
    iosClientId: '524201570404-8go24ti4cop77sch9r05o2d0ghu5cv07.apps.googleusercontent.com',
    iosBundleId: 'com.example.plus1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHIw9tWqNp7E_bMsFO5ng2N4v7CCMC-Ik',
    appId: '1:524201570404:web:fd8dae93ab1f2d958caf71',
    messagingSenderId: '524201570404',
    projectId: 'need1more-1ebd9',
    authDomain: 'need1more-1ebd9.firebaseapp.com',
    databaseURL: 'https://need1more-1ebd9-default-rtdb.firebaseio.com',
    storageBucket: 'need1more-1ebd9.firebasestorage.app',
    measurementId: 'G-WQ4QPR6ZWY',
  );
}
